name: flutter_web_seo
description: A flutter web package - for SEO purposes.
version: 0.0.2
homepage: https://github.com/dip-dev-team/flutter_web_seo
repository: https://github.com/dip-dev-team/flutter_web_seo
issue_tracker: https://github.com/dip-dev-team/flutter_web_seo/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - seo
  - web
