name: flutter_web_seo
description: A flutter web package - for SEO purposes.
version: 0.0.1
homepage: https://dev.azure.com/dipdev/Flutter%20Web
repository: https://dev.azure.com/dipdev/Flutter%20Web/_git/Flutter%20Web%20Seo

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
